[package]
name = "lingora-tui"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
description = """
Lingora is a free and open-source localization management program that analyses
fluent translation files highlighting discrepancies between reference and target
languages. This application provides a terminal user interface; run as `lingora-tui`.
"""

[dependencies]
clap = { version = "4", features = ["derive", "color"] }
crossterm = "0.29.0"
fluent4rs = { version = "2.2", default-features = false }
lingora-core = { workspace = true }
rat-event = "2.0.3"
rat-focus = "2.0.2"
rat-text = "3.0.3"
ratatui = "0.30.0"
ratatui-themes = "0.1.8"
strum = { version = "0.27.2", features = [] }
thiserror = "2.0"
tui-tree-widget = "0.24"
