[package]
name = "lingora-tui"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
description = """
Lingora is a free and open-source localization management program that analyses
fluent translation files highlighting discrepancies between reference and target
languages. This application provides a terminal user interface; run as `lingora-tui`.
"""

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.29.0"
fluent4rs = { version = "2.2.0", default-features = false }
lingora-common = { workspace = true }
ratatui = "0.30.0"
strum = { version = "0.27.2", features = [] }
thiserror = "2.0"
tui-input = "0.15.0"
tui-scrollview = "0.6.2"
tui-tree-widget = { git = "https://github.com/EdJoPaTo/tui-rs-tree-widget.git", branch = "ratatui-0.30" }
