[package]
name = "lingora-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
description = """
Core code for lingora-cli and lingora-tui.
"""

[dependencies]
clap = { version = "4", features = ["derive", "color"] }
fluent4rs = { version = "2.3", features = ["parser-chumsky", "hash", "walker"] }
futures = "0.3"
icu_locale_core = { version = "2.1", features = ["alloc", "serde"] }
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "2.0", features = ["full", "visit"] }
sys-locale = "0.3"
thiserror = "2.0"
toml = "1.0"
walkdir = "2.5"

[dev-dependencies]
insta = { version = "1.46", features = ["filters"] }
pretty_assertions = "1.4"
tempfile = "3.24"
