[package]
name = "lingora-cli"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
description = """
Lingora is a free and open-source localization management program that analyses
fluent translation files highlighting discrepancies between reference and target
languages. This application provides a command line interface; enter `lingora-cli --help`
for further information.
"""

[dependencies]
clap = { version = "4", features = ["derive"] }
lingora-common = { workspace = true }
thiserror = "2.0"

[dev-dependencies]
insta = { version = "1.44", features = ["filters"] }
pretty_assertions = "1.4"
# fs_extra = "1.3"
tempfile = "3.23"
