# The `Lingora.toml` file can be provided through the `--config=path/to/config` command or,
# by default, as `Lingora.toml` in the current working directory.
#
# The default values, if not provided explicitly or by default, are shown in this example file.

# Default runtime arguments
[lingora]

# The canonical and primary translation files, or paths that will be searched for translation
# file.
fluent_sources = ["./i18n/"]

# The canonical locale against which all other primary locale translations will need to adhere.
#
# A valid locale must be provided.
#
# This can be overridden with the `--canonical <language>` command line attribute.
#
# Example:
canonical = "en-GB"

# A list of primary translation locales.
#
# This can be overridden with the `--primaries <language>,...` command line attribute.
#
# Example:
# primaries = ["fr-FR", "sr-Cryl-RS"]
primaries = []

# dioxus-i18n settings. These settings are only applicable if the `--dioxus-i18n`
# command line argument is provide.
#
[dioxus_i18n]
# The default paths to search for rust source files the use the dioxus_i18n
# translation macros.
#
# The setting can be overridden with the --rust-src <path/to/src> runtime argument.
rust_sources = ["./src"]

# Which type of `with_locale` method to use:
#
# Valid values are:
#   - includestr
#   - pathbuf
#   - auto
#
# `includestr` will include a config entry for the reference and target files using
# the `include_str!("path/to/file")` macro.
#
# `pathbuf` will include a config entry for the reference and target files using
# `PathBuf::from("path/to/file")`
#
# `auto` will include a `with_auto_locales(PathBuf::from("path/to/root")`
# for each folder provided in targets.
#
config_inclusion = "auto"
